name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install OmniSafe
        run: |
          python -m pip install -vvv --editable '.[lint]'

      - name: pre-commit
        run: |
          make pre-commit

      - name: flake8
        run: |
          make flake8

      - name: pylint
        run: |
          make pylint

      - name: isort and black
        run: |
          make py-format

      - name: addlicense
        run: |
          make addlicense

      - name: mypy
        run: |
          make mypy

      - name: Install dependencies
        run: |
          python -m pip install -r docs/requirements.txt

      - name: docstyle
        run: |
          make docstyle

      - name: spelling
        run: |
          make spelling
